### PR TITLE
fix(rollup verifier): nil pointer due to missing `CommittedBatchMeta`

### LINKED ISSUE #1142: rollup_sync_service: invalid memory address or nil pointer dereference
#### System information

Geth version: `scrolltech/l2geth:scroll-v5.8.23`

#### Steps to reproduce the behaviour

upgrade sepolia node to v5.8.23

#### Backtrace

````
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xd4c11e]
goroutine 4267 [running]:
github.com/scroll-tech/go-ethereum/rollup/rollup_sync_service.(*RollupSyncService).updateRollupEvents(0xc003943360, {0xc01a409400?, 0x5, 0x20101004bccab?})
        github.com/scroll-tech/go-ethereum/rollup/rollup_sync_service/rollup_sync_service.go:290 +0x89e
github.com/scroll-tech/go-ethereum/rollup/rollup_sync_service.(*RollupSyncService).fetchRollupEvents(0xc003943360)
        github.com/scroll-tech/go-ethereum/rollup/rollup_sync_service/rollup_sync_service.go:207 +0x20d
github.com/scroll-tech/go-ethereum/rollup/rollup_sync_service.(*RollupSyncService).Start.func1()
        github.com/scroll-tech/go-ethereum/rollup/rollup_sync_service/rollup_sync_service.go:147 +0x1f4
created by github.com/scroll-tech/go-ethereum/rollup/rollup_sync_service.(*RollupSyncService).Start in goroutine 1
        github.com/scroll-tech/go-ethereum/rollup/rollup_sync_service/rollup_sync_service.go:135 +0xcf
````

### PR DESCRIPTION
**Pull request by jonastheis**
## 1. Purpose or design rationale of this PR
fix nil pointer due to `CommittedBatchMeta` not being found in the DB and add rewind of L1 sync height to recover from missing `CommittedBatchMeta`. This is most likely caused by a faulty L1 RPC (missing or out-of-order events). With this mechanism rollup verifier should be able to handle and recover from such a case. 

This should also fix: https://github.com/scroll-tech/go-ethereum/issues/1142

## 2. PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [ ] build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- [ ] ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- [ ] docs: Documentation-only changes
- [ ] feat: A new feature
- [x] fix: A bug fix
- [ ] perf: A code change that improves performance
- [ ] refactor: A code change that doesn't fix a bug, or add a feature, or improves performance
- [ ] style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- [ ] test: Adding missing tests or correcting existing tests

## 3. Deployment tag versioning

Has the version in `params/version.go` been updated?

- [ ] This PR doesn't involve a new deployment, git tag, docker image tag, and it doesn't affect traces
- [x] Yes

## 4. Breaking change label

Does this PR have the `breaking-change` label?

- [x] This PR is not a breaking change
- [ ] Yes

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved rollup synchronization to better recover from missing batch events by rewinding the sync height further.

- **Chores**
  - Updated internal version number.

### CODE REVIEW

File: rollup/rollup_sync_service/rollup_sync_service.go [hunk 1]
```diff
@@ -223,6 +227,16 @@ func (s *RollupSyncService) fetchRollupEvents() error {
...
 				return nil
 			}
+			if errors.Is(err, ErrMissingBatchEvent) {
+				// If there's a missing batch event, rewind the L1 sync height by some blocks to re-fetch from L1 RPC and
+				// replay creating corresponding CommittedBatchMeta in local DB.
+				// This happens recursively until the missing event has been recovered as we will call fetchRollupEvents again
+				// with the `L1Height = prevL1Height - rewindL1Height`.
+				s.callDataBlobSource.SetL1Height(prevL1Height - rewindL1Height)
+
+				return fmt.Errorf("missing batch event, rewinding L1 sync height by %d blocks: %w", rewindL1Height, err)
```
Comment (Thegaram) [inline rollup/rollup_sync_service/rollup_sync_service.go]: Might be useful to log the height we rewinded to

**Review by Thegaram — DISMISSED** [review]

**Review by georgehao — DISMISSED** [review]

**Review by colinlyguo — DISMISSED** [review]

File: rollup/rollup_sync_service/rollup_sync_service.go [hunk 2]
```diff
@@ -42,11 +42,15 @@ const (
 
 	// defaultLogInterval is the frequency at which we print the latest processed block.
 	defaultLogInterval = 5 * time.Minute
+
+	// rewindL1Height is the number of blocks to rewind the L1 sync height when a missing batch event is detected.
+	rewindL1Height = 10
```
Comment (colinlyguo) [inline rollup/rollup_sync_service/rollup_sync_service.go]: Not sure if 10 blocks is enough because in mainnet, the commit batch transactions are submitted every 2 hours currently.

Comment (jonastheis) [reply rollup/rollup_sync_service/rollup_sync_service.go]: done

File: rollup/rollup_sync_service/rollup_sync_service.go (hunk 1 above)
Comment (jonastheis) [reply rollup/rollup_sync_service/rollup_sync_service.go]: done

**Review by colinlyguo — DISMISSED** [review]

**Review by Thegaram — DISMISSED** [review]
Approved but might make a few changes before we merge. (Let's tag on this branch first.)

**Comment by Thegaram** [comment]
Pushed a tag `scroll-v5.8.49-rc0`.

File: rollup/rollup_sync_service/rollup_sync_service.go [hunk 3]
```diff
@@ -42,11 +42,15 @@ const (
...
 	defaultLogInterval = 5 * time.Minute
+
+	// rewindL1Height is the number of blocks to rewind the L1 sync height when a missing batch event is detected.
+	rewindL1Height = 100
 )
 
 var (
 	finalizedBlockGauge      = metrics.NewRegisteredGauge("chain/head/finalized", nil)
 	ErrShouldResetSyncHeight = errors.New("ErrShouldResetSyncHeight")
+	ErrMissingBatchEvent     = errors.New("ErrMissingBatchEvent")
```
Comment (Thegaram) [inline rollup/rollup_sync_service/rollup_sync_service.go:53]: Should we add a metrics to track how frequently this occurs?

File: rollup/rollup_sync_service/rollup_sync_service.go [hunk 4]
```diff
@@ -223,6 +227,16 @@ func (s *RollupSyncService) fetchRollupEvents() error {
 
 				return nil
 			}
+			if errors.Is(err, ErrMissingBatchEvent) {
+				// If there's a missing batch event, rewind the L1 sync height by some blocks to re-fetch from L1 RPC and
+				// replay creating corresponding CommittedBatchMeta in local DB.
+				// This happens recursively until the missing event has been recovered as we will call fetchRollupEvents again
+				// with the `L1Height = prevL1Height - rewindL1Height`.
+				s.callDataBlobSource.SetL1Height(prevL1Height - rewindL1Height)
```
Comment (Thegaram) [inline rollup/rollup_sync_service/rollup_sync_service.go]: Any chance that this can underflow for newly spinned up nodes?

File: rollup/rollup_sync_service/rollup_sync_service.go (hunk 3 above)
Comment (jonastheis) [reply rollup/rollup_sync_service/rollup_sync_service.go:53]: Seemingly it didn't occur at all in our nodes. Otherwise we would've encountered this issue before. So not sure how useful it would be to have metrics for it

**Review by Thegaram — APPROVED** [review]

**Review by colinlyguo — APPROVED** [review]
