### PR TITLE
fix(trace): fix memory trace size

### LINKED ISSUE #109: backlog:  updates needed for next circuit release
1.  rebase traceing memory size updates from upstream https://github.com/ethereum/go-ethereum/pull/24867 
2. disable memory trace (to allow bigger blocks)

Need to do them when integrating with NEXT scroll-dev-MMDD circuit release

### PR DESCRIPTION
**Pull request by lispc**
## 1. Purpose or design rationale of this PR

pick https://github.com/ethereum/go-ethereum/pull/24867 from upstream.
this pr fixes memory size in trace

## 2. PR title

Your PR title must follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) (as we are doing squash merge for each PR), so it must start with one of the following [types](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type):

- [ ] build: Changes that affect the build system or external dependencies (example scopes: yarn, eslint, typescript)
- [ ] ci: Changes to our CI configuration files and scripts (example scopes: vercel, github, cypress)
- [ ] docs: Documentation-only changes
- [ ] feat: A new feature
- [x] fix: A bug fix
- [ ] perf: A code change that improves performance
- [ ] refactor: A code change that doesn't fix a bug, or add a feature, or improves performance
- [ ] style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
- [ ] test: Adding missing tests or correcting existing tests

## 3. Deployment tag versioning

Has the version in `params/version.go` been updated?

- [ ] This PR doesn't involve a new deployment, git tag, docker image tag, and it doesn't affect traces
- [ ] Yes

## 4. Breaking change label

Does this PR have the `breaking-change` label?

- [x] This PR is not a breaking change
- [ ] Yes

### CODE REVIEW

File: core/vm/interpreter.go [hunk 1]
```diff
@@ -249,12 +249,15 @@ func (in *EVMInterpreter) Run(contract *Contract, input []byte, readOnly bool) (
 			if err != nil || !contract.UseGas(dynamicCost) {
 				return nil, ErrOutOfGas
 			}
-		}
-		if memorySize > 0 {
-			mem.Resize(memorySize)
-		}
```
Comment (Thegaram) [inline core/vm/interpreter.go:255]: Is there any reason why we did `mem.Resize` outside the `dynamicGas` if branch previously? Or it's just legacy?

**Review by Thegaram — APPROVED** [review]

**Comment by 0xmountaintop** [comment]
`if operation.memorySize != nil` is also inside `if operation.dynamicGas != nil` in  https://github.com/holiman/go-ethereum/blob/97f308a98f9f2f557a0815665f6497eac8f469fd/core/vm/interpreter.go#L207-L217

should we sync it?

File: core/vm/interpreter.go (hunk 1 above)
Comment (lispc) [reply core/vm/interpreter.go:255]: old codes from upstream.  The problem was also reported by us to upstream last year, then they fixed it. (No team like us cares the correctness & consistency of traces so much since we rebuild states and align each edge case behavior with evm..)

**Comment by lispc** [comment]
> `if operation.memorySize != nil` is also inside `if operation.dynamicGas != nil` in https://github.com/holiman/go-ethereum/blob/97f308a98f9f2f557a0815665f6497eac8f469fd/core/vm/interpreter.go#L207-L217
> 
> should we sync it?

seems a standalone performance optimization pr.  https://github.com/ethereum/go-ethereum/pull/24048.  

So at least in this pr we will not pick that

**Review by 0xmountaintop — APPROVED** [review]
