### PR TITLE
fix `CaptureState`

### LINKED ISSUE #55: fix CaptureState
Previously we capture some state-info depending on stacks

but this is incorrect because in the "after" state the stacks have already changed.

we should move `CaptureStateAfter` logic into `CaptureState`

1. move [`CaptureStateAfter`](https://github.com/scroll-tech/go-ethereum/blob/468db1d1a2df8a62aefc013a6ac350cbc894359a/core/vm/logger.go#L234) logic to [`CaptureState`](https://github.com/scroll-tech/go-ethereum/blob/468db1d1a2df8a62aefc013a6ac350cbc894359a/core/vm/logger.go#L160)
2. improve https://github.com/scroll-tech/go-ethereum/blob/468db1d1a2df8a62aefc013a6ac350cbc894359a/core/vm/logger.go#L187-L221 (maybe can combine with 1?)
3. record "after_state" for `sstore` (need to think of a way to keep track of address & value, because they were in stack but now stack change)

### PR DESCRIPTION
**Pull request by silathdiir**
Close https://github.com/scroll-tech/go-ethereum/issues/55

### CODE REVIEW

**Comment by ChuhanJin** [comment]
Can one of the admins verify this patch?

File: core/vm/logger_trace.go [hunk 1]
```diff
@@ -57,7 +57,8 @@ func traceStorageProof(l *StructLogger, scope *ScopeContext, extraData *types.Ex
 	if scope.Stack.len() == 0 {
 		return nil
 	}
-	key := common.Hash(scope.Stack.peek().Bytes32())
+	stack := scope.Stack
+	key := common.Hash(stack.data[stack.len()-1].Bytes32())
```
Comment (0xmountaintop) [inline core/vm/logger_trace.go]: can we revert this? I don't think it;s neccessary to change this

**Review by 0xmountaintop — APPROVED** [review]
